modLoader="javafml"
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId="noclip"
version="1.0.0"
displayName="Noclip"
description="Toggle noclip (N key). Requires server install for multiplayer."

[[dependencies.noclip]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.noclip]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.19.3)"
ordering="NONE"
side="BOTH"
